apiVersion: v1
kind: Secret
metadata:
  name: hook-proxy-secrets
stringData:
  token: ENC[AES256_GCM,data:qNZW/Cy4HspHToNHuxN1EdJTxgLcaSDv5lAg71DlFMDj2QYDmkw8nyt6/etBoHWdDcWdn1bUn/TQlPpPP5k++QIFjnHCmiURZWfzsqRTBjyrYLXVdY1a5Tgu6FIDtK+Q4Rx6LgBonlBtMOfoZCqUOnOP+LKGI0VYnzy1/vClD02ze9jgaOqdc9tY6IM//jeI4x/9MHMOBPlu6mUqfBIwl0BBYS6O+3wVsW/zhpBkhtSgwsDhulaW,iv:4EQMd3F8tpfkR6UwIUOeGDJNBZn8RpyppB4mEj9rF9w=,tag:frFF46ByKV1Taxc6uGAAqA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dmliamVGZld0RjRZSERr
        NHZtbm5mMVJrU1Zkb0pjcXdhODlMYTdpS0JNCjNKMVl5eklDR1NjdXg4a0FXUk1O
        aER5Q3Nhb1hjZTVxbXdyZHYzOVlGM2cKLS0tIHQ0bGJCN3ZzT1g3WncxcUdWNmNH
        eDdEd1NLYjdwUFBtcE45bXdydGlpQjAKe3kqqk43cyEqEODYRQjj4acdqDWqCkjd
        WZfdLxs9Xbh3ZTNlMDIccfIhjPprtBv4vGl2ttcxrx541Q5Cpb2+Aw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-16T08:27:15Z"
  mac: ENC[AES256_GCM,data:qz3P5f7kYVwG5RbR5L7d06u+2k+6I4kHe/CT1FndnFbzSpmv5MHF0xuVAgcGFWIHdM/yYaNu3D3qmYSrK4ApQKTC+I00XysyxqjKd5g3YNM8tpevx9114AFOWO3/QYdCQnL0jWz9HZxQWJq/XtF9WyXXeq+s3M5qoE19jpK0Xes=,iv:R53BPbhT+JGhkx6letSZjfz2YGZ7MyWE2ySihRl8a04=,tag:CIhMhpWrcF/2Nlh9iCqduA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
