apiVersion: v1
kind: Secret
metadata:
  name: victoria-metrics-k8s-stack-alertmanager-values
stringData:
  values.yaml: ENC[AES256_GCM,data:FhtT0LJivbGBFPyVVKXtGJvMN2CygJyOCxQAd4taU/DY64T4YCXIwFf8Juwd18PcMYwaGkJFxM01hgiCI/drDq1/EF9R0Sn4+sbUL0pNj2DUOVhK2/OB7E/NHMpeYBM6oTM8sGiqBuxk32qOol58UAyMxIvtt4xCzHCAuDBY5anb2A26pXpIlK+fx6aBnkT692ssNHcYzD/gc3RaBxQyklDBnX+oiN3wbpl3hp+93mfAHPcXkb4wFfAHa6HV7fXZLDW5nLUiTEthBXVXzImSLcYFsihW2eannk5oaOfa+Jh40DBVHHbNlLryKvPRR7h4eVKi8XR9Nxrj7GKWJz3Nab9QX5ekf9DtwyfWPAJw9FtdafCD47U2QMBGXx+CchP+63OD0CCNSNbS39m8A03aeKSu2ZHx0kyPTXHHZp+3TQOU1ugMPwr6atvV2aSIZxiUhgQAZSUXH2nz/BsUencIpZG/Hqr4BoPO1Ms2+Vm0ui2jU/WbOTGFT2pZm36tJCJS0fKtm+CVWNTNVrX9ZBODKsUxt1HtoYCF0GFzY+oUtR5l/xmLCK8KmvV6tz4SPc2F6h74tEq5Ph1e0p1wHiD+K628D3PZTvKrHNI6ikGic2NQBNn5XvORpRgiP+tjke3WISXo,iv:SZXGtdXgDqbBH9Nvs0sLlHnq62gSYT6CKZXTPN9hl60=,tag:7TTqH3zU9WWuJxrBVa3E0A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UDN0N0RLc1FWVURDTGJu
        d3h5R3pXaGZ6UnpGYWJwWVpqZkhabk13dmlRCjhldDQvd2VGMGpteUQwSkZmL1dF
        VFJFK2dlUGhPeHVmSVBYU1l6TXFlcjQKLS0tIFlFMHRhNTlBU2ZIOGhCKzhTUVpZ
        N3crL1RXdGxDVk5FMU5hTFNBamtSazAKkDvUOj48B0UwWlRNXNE4mqAhcnY/L7bs
        LOPTtvU+XoJPEfZKWLJa4E006k9oh55iTg7QyAKqhE+l5aeBFTc0qA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-13T19:55:37Z"
  mac: ENC[AES256_GCM,data:NcChmoZeGyJKcLE2yX53IGdQk9D9Yc7lV8aIikXlojvton0Ln7kzWDPkWaZ4eSrLweJ9Quu2D8PH400temiZvCWRSrE7o85TUentCH9VMx84XWvmJCZDp+cEWs8v+FgDWVfPOWyu0oWN60k8mHuk7Cqleve0yVQnJECAsEWq7fs=,iv:x9XycL7cL7Ol6am9apB0GbWkz2fAmaXg+STrEYQ0voI=,tag:LwF21lRBmBfa8ZQWTAwO2A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
