apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-ntfy-config
stringData:
  config.yml: ENC[AES256_GCM,data:vZbBlSwr2bbEOU4kEHb7O0od4jxR2tml9lpSZebvyiKdOdnm9OGZESQ9zfG4OFHRKwwS74gvf6A9Eq5p+v5YjWWm4/YgzZll52VyOX2BqbYy1GGg4B801ARgNtVzdEg93SiH2t+3lNUcWo6SarAMI/NawUctCsxAQ8GrrlNo97C9Gl/+g8O7Gs6wT0TTNVr2AhpiQ+CiCucYaDRni9FqGnwvBgAMntQ1JCa5QHXJoTJyFbxRZ0FYW+iJ15X67jOXMF5m+GnAYTdismiEIkiiXMDJEAsQnGF5R4fw7RoY9Bzu9mbFyiGAvV0wlJEhPjzNAr2+TrPRUB73brgMId3jj5zZVSuDAfAC7TMoXs5ef4FGGMMdiMG5AANTRNMEINVmc92JF6AjLsBIsw4mVA+7OihfD/BuTjrv3dVdGpiLqY5e74rZFR8dfOLyyggP9jqKSW8ARY0a1kiWwWaaOIBjQS/YSQU4V7m3daHifcNn5Kx1XJzMZodhTGUMX85KRNndtLOr6qZ7FPECq6yiPhb2mgoLYBwOXR7DHSctBoTZhi31LvWjK8x+TMZO3RWDbvxfYvXj5tKeHsssp1cNELeTCMPBTDrFHh2iLQmAMdgKHJdu2MmtHO65jO1fH8pUJkJCBsvoK/k/J9zIPZHIc2DxkZ1rkCjAOYiRdUvgydmfL6/PK6yKPuWe6IXoNjFwkyP8uoYH9RxllW1qhkjlJneMzZuTNIkAboSdIAR1LEVlksSV8/isG511tJVy4eGqgiLAdsN03C8gvTxIYAhmtonQ4lv2aHdbY3mB2G+h3r5uCyloRfZD/iqXgglKYts5EPyC83NY5q/fm2PNenu/hKakmy3r1bdh/SEEDfhjmm2D0Yn6UBHGUKCN6gFhvWfDEv3wCQsaCEF+tbIxpZpaIBgOCG1Dr06KBUmpZsiBBychqtsXyO5COQ==,iv:gg8JrgLrngchLYJYSvoEoo9yBdYZJt9BI5IM7CebBwQ=,tag:/9oycQcnHfWdYb7AzBuP4A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkL2dPc2ZYczZ5dkQ3YXB0
        ZE5Fb0tIODFTWXcvVzNSQXRxdmFTMGFMRUdFCllvYWRDMW0zM0JVbUxwOWNnUTh5
        SE9rY0FkRy9EZDMvUEk5VkgxS2JFWGMKLS0tICsrZG9kYmxOZHFIOFBxYVI1ZlVt
        VDVYUnJibElubndHMnNva0kxd3ZQeGMKIcHZ04MwRf9Pht2JYXSiiIJ1GcGKAp45
        3TZJeByHvBIEZecYB3lEc8a0oaDxC0g0BX552QJ3RaUZhGp4UNFdAA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-14T18:59:53Z"
  mac: ENC[AES256_GCM,data:ok5zMBWeU9G+2UWQpmyC6iDyHsEjTRMFT1D098XY5VHF9FxJH0PKDFRDPSA2n+0XQf4UBlroYJ59SGjIj7T2TCV9Z2eE+AG1o65pPFDcqtrpiGJVGvG/+lNIm0oMN3Kl8j65NTSUDXnZ1NaUjfCFDFjVMCVhRTY9hJdQXCw9gDo=,iv:ZHwo4C5ODNFTRJ23eyRROBTw4XYjsVazjxyS3c5f9fU=,tag:PpF3T6d3RAy55Zrha+8sbw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
