apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-ntfy-config
stringData:
  config.yml: ENC[AES256_GCM,data:HvNIdt61YUCtPs2t42aJIrP40yYXO9wzLuJZJ5cUtR1kKlAk8iCNZX6arpr3771wDGCiKFeF3d6C/McMRGJ/xWFOgpC19oKxj9HkZggi8IhP1UXz+Byv5VfqSV087gDDsgZPJTeqOO5jtr41XwMB2lqwqR4Hn/GKYxg1vsd4KuFUJgTEjyJTavne0NiK7wMnHChM+usZVYekhFvK2ZfmsKM1ete2Amj+VMTm1zHCYYbTWBFkosiFimbQO0uvz87Qj99iUMBafX6Xx5YIDG83hDF+01AHIPnfQJoLjSuoPS1njO7CdnNsGFyyGKvl3tvH4AL8MwQlo3875GKbFhgXKz5yI4N9v2tBZgpjqAqkOcZmtjkGhC/HusIGOi7IxkeRox1/8v8bTZ5Txis/LDe6wIUnxGPmAnukZHtkWLWkIpVLVPrPfWrdxLz81xDLV+4z6ubTTe7ShYwHTJ36BYGKfMjX2kADLZtAjz4RpjL5UhtvyYYYsR8mt0+bRstuYRan7b8FRqcHHO1eE30sUm4oxWYg/0+4AXkw4Uk6mEVI85++AWZy3Aphc7JFYWsx66ANr0K83fzthdhujDwmanxTlj6Q+a2GOQA0LiwhH5LQqhTXkiShCJml4biKV+HBsINei7dfQzlOHxjXjO3LaNQsTCCJevW1J4HRCF8+59s2e+tpq87qPI6yVBtymZr94/hAYmN5jdESpKL8pRVkubw+ncRRw2z6sPsYSV7+Guca9Qfs4/QSxNV+j0E2gz3J9ZlV9IzICzv9pU8BHUsfPhdZ693KHHbUc7jdKYQ8sjZnO3Zl7cY9xQ==,iv:21gYQ02cR+v7q3yWU8rlDwKipd7NxNFA00F9I7mfqqY=,tag:0cocl9vflymb7YtKR6+g+Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSHEvRDVzSWZrK2NLTSsr
        VzYxcTNzNGdUckYxb2FoeklUMzhGRTFEL1JZClQxUExCTFVQeVhWSm93bDNBb0xS
        RU9tQ0gvcmlyc2dkSEdtRnlYdVdNcTQKLS0tIHBqOHBlaGJ5c2Qrc3hKVGdLMXVo
        aVNXV2JjdzFRZEJJZDl3a2ZaaFc1UEUKUFknLV53rAylYzHZVqwYiYyglU4hyszS
        90lTO+240sZLQwZuL88bbrqEIexWORKNPJ//7vhcA+EaFBdSsh+45g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-14T18:52:59Z"
  mac: ENC[AES256_GCM,data:2DGkOhA/xSN8Tp80Hdr77fpY0/rjWFNaGZAQy5NFAi6Wao2F8KU9qayY7QANKlkaU0OCnutf25Gq9B1pUvWhB9KL/ITYjaVkMpRtjVX6M9O9N1jm1lwpITSwVl8MzsJduDWkY+uQx1T/TSP8Mjibxj+SacRMmwXqi7Wj6Q5nqXI=,iv:tjdNUh6BfNuiL6XGwrkVAY/bYBoo/foYSqgaAmMf3ys=,tag:2iMibWKedXkraJOgP3oO2A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
