apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-ntfy-config
stringData:
  config.yml: ENC[AES256_GCM,data:lGBNO7/FsD+oBqRdOcu2AuRdpVYZVUNqwgFV+/GfzGorYx+Sr6v8COo7fKw9yG/ARXTHQJDKXMkfOAT9DOWeoiSou4QiHfEoE1P+mL8RA6YuwRi8cT5/wsX3c23VE5cH6f2hGSO4GombOXKChCbJGCv6hBZCBQwyPnkQLVua4IUEG80+C4IUe5U2wQyEDSq4dRApgZveYGu+DN1O3cbdgXK94m5bjIpFjXu1ceNZx2cUjgJjg1+xvP+x0L4e+wQ1DOhmGb9DRZPGInxzC0MS5jfsSMaxnjqMWDG5pcqEyQfz4sDsLQC5+AjHSpqhA0/98D0GHhPKkk8UW2h1IjSY+cMasOFBSm1zmTRTtO7YNP38Ixc9M3AmmRHi912vAqEjgOxDZAEy7MPGKtL48K/YfE13UDM+IBvqP1uG5Asl1rVChNPPmgSr0KXEBGdOnSzjdgxdkFooSHssKAVtPOkqgwnF7stlv+RfN3qN0tzlQbi7yqGqUnTlSeEgNktfoAlpNxFlfkVZIZL/MsMqKzQReup9Zvi70PsuZ0TuI74T0+3A7O2MBzjhriJDmy8nc0v7C2kKPHlDRHtH6Ik5FHA1zd4nGrmmQVHMQOYXPHjf/0p3us8zSyHzU8PToiP87oAeinobAvSZ2AUmE0kGTE9l4TDR4VL8mKcc6p7qScqP3KC9ojDa26ZojI0oQRey9k361L+Iz+p+NDhG0xI9zxmZK7E/ajX14Ge0afD8BmeaQK6uWp7xC0FSdM1cDPZmX2jza86xlbFrzk+o,iv:Y1+KCNMGYhJlHAx6n+SyQlFoNgFFCfyiVVA/ZrIpRjk=,tag:WTGBreceETf3TFXpR3A+rQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOTJPSVNxZW0vVWgwOVcx
        Tkk5R01vRmN4VFd6SlRxeVJ0VTVRV3RnYmlvCmsya2QwNGxxZ0trMm5yQWRuR3Qv
        R243SWJTLzF2MkZGaHJzcjhSMWVWaXcKLS0tIHgwSGdCdE1aY1ZtckpuYk81b01W
        Z24zMjZiaS9uSFBZL0JocmxIUHdaZjAKnEDqJvuARLQcrH48vPz3kL2ZjeqHv6YN
        KVvktBifh5T5d6KFHDzQfOhu27X2gn7kfLjzSmYW0Ea9qHjNdFh+qA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-13T19:55:37Z"
  mac: ENC[AES256_GCM,data:duRhzKjVxCgHQ+bgENKT6aUGwapNz/p8VgJ24qwrlYwqzGeHsOyOcrIpXmoaLvsjZR1humif4deC4dw5/+P6bxZ3/I4TRzLCaTwK1CQae9UZlC9Hawe5JmxERaqcSVwGUh4h+DaAF90My0Vx329W6rf9fKxXeDsTZOFNJMjFulQ=,iv:JgTBuHGmNmhed7IR9530uaHnhpnp4G3VscPKl4O2/6k=,tag:rRUPJQICyM55B3wKTbVtPA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
