apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:loCWy920mBZI3K1/MITzjdHDAGO1deh/KaHeNYdXf2agVWAGoJTkvrR6NeJJIi6z2kOBAD4=,iv:UfzNLI0qhGcvTE2YaRvNGoz8a7uv6YgPNnxxdB1fO00=,tag:U3IDCegRLi8VmEbLLeApug==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WE1KUnRsOWJkZmVoUjRW
        RFNLSjFrbjB2cjVwbXhJVXp6Rjh5ZEtMdmd3Ck0zZnlpblJmblJlMFAvT1NyM0ly
        dndsa2E4WEJMdldqK2VvWFZUTE9ybmsKLS0tIFl0VTAxdGhyY1RuL1J4UmRBNXFJ
        a2QxdU8xOTA3NS82WmRVZkMybUZWK2cKFk1BFY65O694JsuoNhaVxJ4JaW35YQ6D
        BV5TAIcVd/TuGwixrExPd3uijYH6anQwO0Xk88wZ+xN73OYd8Ogdmg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T16:10:04Z"
  mac: ENC[AES256_GCM,data:h/jw2HzwK7x4wpndUMPb4bSOQuD6z7n6Dk6JSvddzp4GV5q52ohvkVbfzEPgcWmXVFXOT8cVfGJpQOTnOrlEvgGejO4Wmogb4Q2Y+4kzDUDyaKmT6rrGIJUti2F4zRxBXeGPNY1eRaSJtlTTWGYzoVxX0K91xObOUgjwrjssFSA=,iv:+M+IffeZvgo3NiXEqYXotgDkkffGbNzo0LDiwSePZmE=,tag:YFGt6h58tJb4VinBaDN9nw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
