apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:SOdP0Mp6Gaz4SLxp4xtJNxGVaafuyl2dcdMVkM9B1cpIz2FpM0CV4eSvKSQEawloT4Eif/g=,iv:kWXdi8UWR1t8Iqsx80eTXPUH2v8pk68jE0uvZtIhddg=,tag:gGU+KtWBJ+5ESuJfO1aXXA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWDZSWjZWZW43SjZRTjRt
        U25xdjhRc0E4MHJxcFFNWVYvWTQrWTd5Qm1RCnBDK2NEL0lwVTRLVS9BaFNDbUtL
        ZjNLUXk4YmJCNHloanRZbFlRSUJLdlEKLS0tIDd6azRHTUk5aysxVXc5WExMdUJ5
        WFpqVFExbkN5cDFXK1dOUFVheHY0dFkKiEcoGtJWDhfrja7qHpDGNqJRzm4XljOM
        Mf3zhp3WCzozBraY55C0jVuRT+l5GK1lpdy9UQ47UzCSbMxjI3BGQw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T20:07:30Z"
  mac: ENC[AES256_GCM,data:J2Wnccs3K96xen00mMuduWhFhF1aVq8EeLTK/1AWtyTSG3F+3LsDgTSR1irl9o4xzO0Mw7hq3o80pGBtaGviIEfUweL2hyZvS+geETkYjhHrHI/O4AYO6Qsj78W20/u40Sl1kAsqyfGF+dXa5Jw8GjPkJ8KEN6MNLQpq99rC1L4=,iv:Gef5KZ1qCMB7GK72XMtOTzYKxldHqFZkJhk7B6bH5UI=,tag:rFjL2tu+CwdMJaPLyIJ+DA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
