apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:3Cof8BSG3WHEkGs6Xg5dXLKUPoxegGMuL7HG+bM3BhscpIVfJyoZTsp8f0iR3oVFFDfeFs4=,iv:dyZjqTIhy0ugIMWG0W/Lfk3F3ct/TMvinrn99suhyDE=,tag:K0Q1iA4jW5HpuDDsTD+DHA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVmtPSXJFZ2hpV2FKSFVC
        SHhueExvU1YyWXBobW9GQ3lmY1NXaTFqUUVVCnZPUDhRSHN6cm1IcmxsanhPOWlY
        blhTclhKVGlsZ0p3T3Rjc0h2Z0d0dmMKLS0tIHFVMFFJOURwWU40N3loNy9JVk8r
        Q0J6NWJNVWRhcXp0OG9UV29rQkRiTG8KeLc82izNAJO6fjgnJX7T0fLCpxHtDevY
        RdmVrIhY6YbqKCCcqDURMoIZa9KzryXFCh0MWvCl0mw95YnPOT2dGQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T20:06:18Z"
  mac: ENC[AES256_GCM,data:ZmvbDvIpRBSy6LBqjH326wVSdejkw/7gKaSRT8DdZ3OcidlU07Zv+V18KVrRih3vtISE6Pf3y7bGQHG++HldcMchqs4CBM6c3N0erI2RLzaMthq/EmIEAmASPvlXJnXEUDAOOYZBjzjnop7Fg3woxV1u0dtMujdP0WsIhOL9Z78=,iv:vOodzIRl4xt73Oj0qRGnUi4BmkZkZWjUG6Kd9oKXtFc=,tag:aOM0BZLhYBypFYekmyC5cQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
