apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:QBGQO23R,iv:zjNs/fex5SJbqvUGxljEFuVsn34cJGteLCfWjKAIkoo=,tag:mYUzYml98yMeXmkJBaZ2UA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSU80WjkrL01JcFZvSWYy
        N29JN25LMkFVRlVyemxENWlob1Q0TFhzUHhrCjhDVnllNDQzMy9McE9LU3JKMnBN
        cVUyb1ZQYWNqNDhFK3M1dlZXSFJSSFEKLS0tIHc5VzlXY0FFbjd0UW9ydWhISzhS
        dlZmZUNmOTVDWkJtRVdyZGw2SDZ0aWsKbFhnEdqLkqYx9smpm7ZancffgM/e0gwF
        fktYE3q+YcV7YBY6YBakRDeTmA800KN+KW1yKHn+pEA4vk7sEptFtA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T20:07:30Z"
  mac: ENC[AES256_GCM,data:By0RQjXJdtnG3Qc0Dd640Wa8ZBp201Cn/6RPp+t6cjnCPy8HEmdLjwPxx3HYKx+9kOw5PXw+rdThpcRRVcGBAgnq2B4mSiVQbQwRKSDh4y3e1dp33BeNBnuNeqxihpVO0wMwvR22aUA0oEm53ozuUwDTBipY3tJJCUTvOpZLs7E=,iv:BL+aPP9jshehyFYyK4NT6DFVWbhzv9VirOMzOIawuSQ=,tag:Xck1dLYdfeUztyi7Obxv9g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
