apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:C7i8ap/F,iv:XMM7gZfbCUjoIvY0MIxHUrRt+uYzUMuXQg7nPZNLdzI=,tag:7wM7FLX4yiND1hK/emmdDw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aU5SNS9yeEQ0NEZzbmNZ
        R3crOU5PVmZ5VGsrSXVWaytZbXBRZnZTT2xvCmtTNSt5UW1VNm5WV2F0NW14cnBo
        K2RZYlZvK0NwU1dQeGg1SXRIdzVLaGMKLS0tIHdXY05MWlplMTUrSysycGdqcjNp
        eVRHL0VqWkxlTVpWOGk3NTYrSXJGamcKzCXd0CfFaXeDMjOqosH3MeJO7ncmFsB1
        QrAXT/EwvqI8l+BK7TDft4jBHBFM9SP0ksPs/zDIta1SZY9Zl6fH/A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T16:10:04Z"
  mac: ENC[AES256_GCM,data:PxGg4ufMQNJgRxtTQ6mL/OdLbYASIpTwb1QfCUEMXw47STB6/YOka3zrNvVKlhkdzXoaHMOoLfn4X9ZBShquQTlTLwxbruJWABRg9CcxvDM38U9ueRGCKLREcw1JEbsP5hzHkWmwKd6dvlylF1d2gQtxy1MzmwjQ+UCxyxKiUJk=,iv:nMci7/SNP0bDFZ2U17xQYXpm5Bzl4Q4c5HChjajoZho=,tag:bb6J6gs212adPtap/o/waw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
