apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:r4F3ebfp,iv:mqw5ZoIYyujkxpcDI3OAyM1eChxeu7iku7W51rZcPyU=,tag:M0W/3IZ8B4WeGmvMCAYMOA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MUlIdUdWNEFkYWtFRm80
        MHRGTTJteHNjRzhXV3VDd3lrMnhzdHlKWGw0ClVTQi9BRUZBMlRyS1N1TEptNmln
        bHFkU0pBcmw2UXh0eUFnb2o0ZjdrRUkKLS0tIHZERHN4amlXZk1iMDRXYU5BVC9s
        bHpWUHdCbzhPdy9oeEN1aDRzVm1RL00KyVc1bvt+qR70hXFeCJXyiAuYKcEIbpJV
        ayZ5HBjbylAxRI4Z/YyQw7vPSeCq4iGK5H20lCC8V6C1OqPQpj6lLw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T20:06:19Z"
  mac: ENC[AES256_GCM,data:QPyscbGUsaQ4k2umD9dYCmUPzeYdzQ4Lt4neO+3KLa2bJsvHknFWtLjOWSEj7QfRYYqC+bKtWYdYuuASSjiWvrmtut6GCG2GNMcpivZ3ngRbunBSSUAz9pyjjFYP84MyfSsOkMqAOoCkNep7l2XjYw3mgzeL/PIYV8/3FoZgW8g=,iv:FPGR9Vt+GyGQ5MWbzWkoa3FuS2ItXKyslkL0CezWF8U=,tag:B7DwRanzdLDh/3gAcZjXwQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
