apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:Mys0341tQK3i5ZGtKEtst1CVITs7uWY0XT7nuWo4iGw=,iv:qxJPWFwxcBjqp1vN/rsWntgyZFxSD92T2xQcDMsYDqU=,tag:58a0TKqSxTrLYF8ri/ka7w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTk5OOUtVdFpnb0FOSFhH
        UldDMVVRaEpSK25uSXI0K0ladnRrV3hQbmtjCnlUREpGWXpvWmZyZFdFdkRxUnY5
        OElzUzdtTXNjUld4bkgweGNXSDE5S28KLS0tIFljVzhxSEhTazhuQ29DRXg4WlNW
        TTR5YmxqOG1OUTd3QTJlWGxSZzJiaDAKKgZHyTF8Lm8BncJiniTr/nUmjXXNGv0j
        HmwGGC1NBMVwahbaJgFKQ70599BI7A9a6qnCuGsm/uzzgJkWtELbAQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-16T17:40:02Z"
  mac: ENC[AES256_GCM,data:jFUwWLbt0BQ1gvPinDFdAJAGJIL9TZAmVaGVw5RWIbWwPtkXCS1yFHDaijTo5ppwUlai6nqe+cuQkWhz8SRHUuIECL92mO9TY0JCICH4WbxMaDm0/wXJfKsJHvAqBLCd0f/KTrb/RgVytC8hdeSucsFvcJuAI/IiO/i+pnR3X0o=,iv:FxAJquVoecjG+1VR1pJwkq+ZhZl/Cv2G4NF78oVgycw=,tag:fxMZOnzCl11XUSDMqtMkSQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
