---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hermes-pvc
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/offsite-backup: enabled
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
