apiVersion: v1
kind: Secret
metadata:
  name: hermes-secrets
stringData:
  OPENROUTER_API_KEY: ENC[AES256_GCM,data:zGzCpiT2Nit5PZghDG+qrRZNJUqrLCsPgK/8C7gcIKPjNVJey3zyRo2k9B3/pMork6oxfxA4GpfUeeX/1jYWUie9IsC6FrQTzw==,iv:KcnIs2a4ReLmoSWQVllIR6KX7EVpBL2ZTI6wnW9qIrQ=,tag:vs62/w+j85P2L7j/Ui+k/Q==,type:str]
  HASS_TOKEN: ENC[AES256_GCM,data:Lyp/t6jeUlMVl9yaKTb5icf1IgYghuuxB6w4fnMZ4iHJPunZDxlDazk84I6F7zJ+P5Xp+C6CnfPvJhpBHSezbyMe/iJvrg7E9APe3UGkGcmyUGeCdSrVyHNFOK0bIo5xpCXkN9EpPcscJU4YcY1nCadq7l+r/8uhR313DR8a6R8tpnZ7yU5HweCgsy8pNhXEtBzh2svaUyiXfPJxNZdnvuOA/I3ANOULl7h6B57RqtS+mRZdr7zN,iv:LqufeEPfJVY1vn2Qz/SiqnaKZ7tZad/ihTKO32p3lpA=,tag:8+1Hxhlpn7PUnK1JJPD25Q==,type:str]
  HASS_URL: ENC[AES256_GCM,data:XtsyAUVEN6/wvT7MrY+3HjVkyIWrSTfTh3Ro6mFThmkjv/9SwgHbL8QSq94+IZIrfNF6WA==,iv:qP0gXdDc7T+0WDDzNY+KRWOc/jxXeNRt9FnOdJ9r2Ro=,tag:xoBwgDXBcYIt1gnVEK7OIA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Yk42WXltMHlWUVFEaVQ1
        VXpVL3RuVGZQZS91dThnMW9aWDFzMTNxOTBvCllCTll4amF6QXlBRmZRV1FtVTVL
        NFVKb3FvN2VoYmRPNitiTzJHVnVYbXcKLS0tIHFWbGd6UG13SERweTNFUzh0eW1k
        eHJ3VFZhWHBKN3A4ZzFSQVpEc20vNkEK7MLgw1wBBwVmfXs082A/g/hjbdpfCixM
        SMIyZ5Mx4ciHc2pHmhkfTIb+t/lrXQdWqZyT946CLOjH1EtQVGRxCw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-29T16:54:51Z"
  mac: ENC[AES256_GCM,data:buCu7xXS49E2/iiNoFfsXiWRMkIUOgGwys47CBcH0LaNDRA00MX/AHzpMHzGx/ndEBSd8ZbcY7YGuJBPnAcF0KGKxICQbc+wbUa5a+eA7bdQM397LmjDFKD/AD7lEYBw8IMLGSVC2/ITtb785m8LcG+dcIRNmS867szA7I4ytHA=,iv:vTcZQK5g4YXv6jERcRUfqGusoVA1RSmEGTBfFUWPbHs=,tag:c+J7AuCQJA+QoD1fyMNELw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
