apiVersion: v1
kind: Secret
metadata:
  name: longhorn-r2-backup
  namespace: longhorn-system
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:cPwg8gxzNl8wm57blSmZmsUaHf1CJ4jIuN/UzwaMgG4=,iv:J+jMsR5cLQ2pY0RJrvV4Nt/ZRi9buAE4uaFhv2OC5mQ=,tag:5AwA02bb/GX4SRHitzdvyg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:lU5+vIMGWUCvPXtavMZ0HQv50JsS/Y/0k2n39gCKPow8duHBjFr0woy6+RemNNNjbcDpc3zXqDotbnq7pVSMxA==,iv:6z8TfLcm1CtNu5VJb8Nh63HB7rHAvxecjNoKoLc+rFk=,tag:CgJ0guVT+iOpKWRwY3//Xw==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:b7i8f3o7bRnlgKrVloUrwghM4qu4t+M3pi9Djq7bgapQRDRqRsGPmvVDo1tYPhCJ7MLx5EOG/MdNmcSEAhVrIKs=,iv:ttKasdabOr0ID+J3mNVeBUSDjGmlNRV9laaML2tt3S0=,tag:crZjMl9NN313Xz3lmcQt0g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwL2hWQ2J1Y0FOemxsM1hV
        RHpxckxiWUc1dUdVY0dyRTMvSDBDWWlzekYwCitXVHBYR1hpLzJaN3psd0VhM0Vy
        NUZPU29PMkJRR0hkbEgxQXpQWGQrRHMKLS0tIDhVYTljWUxwcjNka2JVdUt2V25j
        eklmRlg2M2szbzE0V2h1SE9FeGRjUkEKaj0jGpaBO8+mQCj+cA/g+gdqQuF35RQP
        DllOx4XfDlDYTKdcH5QWlQbymJ+y8UtQBFGkZz3p8D1xzWkz/4u1Sw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-16T09:47:43Z"
  mac: ENC[AES256_GCM,data:V02BHshuaHR6xRCigLQ7yrcafX4cMxZf4sC5mWvwfTApqCn3Hnf+J/l9h52/ysYRoI696xTmgaU80JDmvAi32A2G+VTpx2IAMGf1JPAHHg2kFDrdBZOCi/o0LTykX+KVzmE3v+7hTT+WWGPHvfkj7AdUl0T+YsbI/R/vdWSM8eE=,iv:UWh7WVMPZeo7PJ1G4hOHoMeF5q7qMmhPC2XvnE4rTgs=,tag:3VQsHO3jFcYnX91rv/+Dag==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
