apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:VnR174w08OPtsLl9gaD79FU52Xv+mVQrcaQD1gOjqC7SUxwY74ZIzcGySoC+UNnp/eeS7BYTwUQs8Wknv6P6LKxGxWwCf54iC0XFrAl/TlOk67S2lqZ3bDaRiXWsaoHKuTWsidAl22TToZBcMs5tCsXy+0jJWej6jzLwcfEuVF06FSpkJy3u5MLbdRE5mZoiWABKzRrov/TnNPJ11svHghGJ7SjPpIAdrbaTR5y5NhLut/4h,iv:RN/Fb6X4tYj1+jz0K0i5CthmlZ/TrjQES6+oFYExrfU=,tag:Qr0GOP3VM2ReVQQvgOR2Dg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WUJCZVdBZUJpTUFMUnUr
        cXBLU0x2YVpCUlFsWkdGUVZSU3lWdlVJRmpzCkwvRHVkVldTc0xKOC9aSkc1RTZq
        VlcxUU5ybEZNNHplRUhaK1FpM3VnQUUKLS0tIE9JMHl5OGkwSktIZVdNOWlGVnd5
        Wm5NRFdGOG9ReFY4OG85RlAyUmhNM1kKIEYy+NS2xpi8VimCg16k5La1iqKUDTCO
        DJBRRmA4sWNTknA31/jZ9k/rjYRmw1CBfp5cmWhSJe/EqeZ4NQfdxw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T20:06:18Z"
  mac: ENC[AES256_GCM,data:NsFfIpDNLxvRrsZqGVacyyo3VW+JEEJd3oBU/pZOptvUzYviwoaXKNvp3m7CSS4YfCmSCfeO6/BPG+clM4PuHoX1CHdxttG1meYMaoBphheg/5tM2fpSXhhtI7B7VUxbi/1SumUalopbAofbArgfXhzsqR49G2nlIS5N1dRLlu4=,iv:fR3qv5ggrjvD22XongErItsuYocR3svRnZMulmBs1wM=,tag:MXvKiGxbCYsSacwzzhYAng==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
