apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:9QqCG8VpToLyH68unU3UfTqvRg2OX9lWHWQcvQS3xlkHaJjR32x2r1QsWpiqe1KrgWe2T/stJcz56W0vlD4tKcaeVPcuTn9rrmfVprRXZYXP1gaK7q60waffsC+dGszD7GyB/8uduxTi1s+B38o7mn/wDQ4aIIfR9I/HCqEWSpmgMFyk+BaRTSCPikiIPYNtJV1ftglrvaqbZGXxShrJH0j9aIjVn/sUW36pu266gqRUzD5L,iv:9Q9Wcqdngm7ifTjiqLEPXjmSPwXyFgV4zP+BrxwrGF8=,tag:k0SHQ1LUmU5WpGHEeUllzQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKOWNuREozL0lSV3JPak5S
        ZVBRTm90dzM2R0JSSkx5c1A5SysycXNJbkNNCkN3RXhPVnJMaHBVY1dTZy9EOHFN
        WVpOY0pLK29yYWVpRzlzMnd2RUpUYkkKLS0tIEtlZVZwR2VvQWRGTEd3TGNWREFq
        TXlvQkRZSG04ZG5zenpTUk9JZ05yTk0KLr3eK6JXI9lvi8okL06yRI5ZNXEUMvUs
        muB0eqcXlIACS2AkvGMH+5vPZ2l46dRIhIk7BaYKvz81X6dshtc3uw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T20:07:30Z"
  mac: ENC[AES256_GCM,data:7Fh45QahLHJsaVQwyw6x2hPVavDWsJRR769SlC9xXsGxIFn7M/4Gue1Id0gL5f4U4q2Zwx/CgrHQWgny7x8PtSGflAw0w5cgfUGxmdfWQTXqVv2NLIAZv4KHvMHyHboExfSFHfwLmMSDO3uRKMQF4sOrNoN/5uWJnMaQzQ1XB14=,iv:JHMrQMQBPd22tw65YPPbX86F8Y/HVkNBEqYd5bKGevw=,tag:739X885F936hfDuszrp/sg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
