apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Qu6poaVEpe8eUT4B/A2SADkjexbtnFfSxG6NvqMnERgou7ZwHjtpqyntsqsIrMwfvAvWGXgIIHw/50D4ZnuSHlK2MG3E8Ul3WSX6bmy57V7OtkHt/mHCyHPnwD7QfJW6SvTL1yVvdkTbzCJu6reDviha8Wev1gU/VTGkr5NfPShZY6vlXsJ5ecdcf2mlyTc6snevzsxDQGs7XIvppmzgsX7GqydthRUxPqjPe4uC/NSKPBqp,iv:gsq8FtyCLqBhQz91ZyBQ3EB4CRhqFSlm0Xrq99pxxQg=,tag:WERHRJgBgq5pwc6vkmO//w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZVU2cGtVbWxTZ0N0Qncr
        MEQyeld1VnErYyt2dWltWGJ5VzhHaXlQUzA0CmNEanJMdEhhaERXb0FoWmVVNUFL
        bmlZTHQ3NUg3dThUb1MxVjlrY1JEaEEKLS0tIExkWm0rQjA3STQvWHJqVncrM1NP
        d3BRaXR0RVU3SWZna0ZqYlRXOW5kT0UK3ap8OlvTS37G/eD2rPvBOxlkJhx0mmtd
        QpziXVfiWcDldHOO28Skikm/E1IKgzvsmuAaiXigDJcLRu6n9inObA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T16:10:04Z"
  mac: ENC[AES256_GCM,data:KXGD4+e5PXNm6MKPAtjc0Hntv72ei06WK+jyalA6sYyZ9Ht3p3EA1+ZfLHZYrwBIRjiqiKvyRpkmzt5eBuzgJBQCSzjE15+Lk/AyX7+ixg69l0lvS8CJ3ZuIEJt7/ERQF7UcTiQMfvU/OO+9qZ+a3HFrLFIgGg21xJG7CqHZjkE=,iv:/mKvqQU2NZXvp/H3urrIpxAtWSUukIO1/MJmn3cnhSE=,tag:il3NIVzBemCC0LGtMLvKUw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
