apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:5i8BICzAM0fDC3r4DrfBs1knn0gtaievRUzrZECSE2fuEd1v1LzLrGPnfjEIx4ECvsqiNb0=,iv:NlSoq1aSk0JQIsu8WN7oGK26NlIRlWdpbx3rvgcRnI0=,tag:bzmMnX+dBZmZeFV/w7rtdg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ckl1TmNSMXVjMTVLUjFS
        ZHErTnc2MzBCQS9LcmhrNkpka3o0YVlLeVdBCklXZ3FhM3MvOFdzbHVkTHU4bUtE
        T2cyREd6WktNNjhRTGdVZ1BKaGQ2aHcKLS0tIEp2OVp1a2RjMUVmTmx1bVJ3UGVQ
        Z0RhSXJ3V1EySE9oUi82RVhhM3VXOEUKR5SyQQcoPnXuZOR3PNrJUWVw2FdVIYtt
        2DAy0wQO/l5udJEOj6l+72s2ao4FUcKC1FIT771j7hpm3q/7WNwfiQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T18:17:43Z"
  mac: ENC[AES256_GCM,data:ndTI637pozQIp0k3P9E+ecOahCSlq1qjGt8Z0uCgZrn+eRhXL2xL0oT+k74IipUrZNBvQaGOSjsNcVv+H5W+G1DHYwgnE6lhJR3DD7Mt7USnHhWt9Z0gDb7DVd8xvpUx5agDN/DJbJWvVACX6H+iIYH0ImNU9CSHj0bst4Hi79g=,iv:XUGEuzOAW4I0iK612I2aJ5b9E7CNcMcQdemAI+kreJI=,tag:e1tohcvw3odhfkLnZGmyNQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
