apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:TH7ChSKZ0WpnpbvVtyBbxCX5A9xQ5pMb1uQBVStYi4wKKK2f1/KBJf97IIbFkeMD+m1qyUQ=,iv:VveRoU751qgHoh+OYbWRwFfoSAC7I6ZfqXKlFI5igX0=,tag:WlyCetMq/y+Hzm7vCB8nIA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVN3h4ekVockNmTDZ0MlpN
        NEhXbFB6TVJ4MlFWTFl4VjdkS1ptSE8vZTAwCkxEeFlwN1EyZnltMnkvT1pxSHJm
        SmlrY25zNUorQ2UvVWN1aWY1bWc4ZXMKLS0tIGw2NTJ0ZDVzTSt3VW52TFEzcVp2
        WjB1K1YzWWxzRWpSUkNwN2gyUWdxV0kKp2gMPL8XzH8Uf+dJmOmbU1uWgmjJjTeD
        MCQM0Fg0RPJY6nJFUIdjaxzAWfspcIzcw5ce7+pNWMTiVyaOA0mnmA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T20:07:30Z"
  mac: ENC[AES256_GCM,data:nacvD/qpgwrN83HleXckf4gXpSvEhKOpF5oEF02fmN12xfSRCSSix8vc71BVfSfY7h/ADaX265Rb7wj6IOj9RvY6WOV/lkq871Vl4g/uUD+LhdvnCrUG+m20Atqt9CIfMsfzPB1xTTkIn16+keppy2dqZswO4S9J8p164NktvWI=,iv:i7kVEZQZ+mdYC/b+BBdnNy15fmRsAfjnN3s9Unp91Rg=,tag:6O+TcRjAGkH7K8Z8SQj4mA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
