apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:66YLCr62Ualx9lW9xc9hH3TP2ueW8zPULmjzHORy+Y0UOi6lcG3eqEUMuft9dxUUJx51hzk=,iv:Bolg3v2Sxa/0GIuqf8PZfI/zyvjc5p2QUXFejZjj6J4=,tag:gYKuJJxlhg6YacdyDxx8MA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvblF2djdVMXdnZWRWQmdQ
        WXUzdzhibDZvZktIdXpYNUE3LzAzNjBPNUN3CjlNWUpaNXRXZmxhVmFyZTMweXFW
        YUd4MHhOVm90M3FHd3RJMkVBZ3hoSXMKLS0tIFcwNGppcTJmRndaWGl4U3RTemR2
        dUtyYXdCVEpnSTdBK0JHUUViS1hTMlEK9vaW4XglTXRpwaUMv3kpbSBdAf3gFhjI
        KxxC7dbCwPE8R3wWpxGYYBu2KxijvaBTH5CjUJwLlfCr9qD9WizTAw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T20:06:18Z"
  mac: ENC[AES256_GCM,data:Z8rUnlLWuhhLdKlkbef2fYbzCWbDCCvq29t7FUpcFnDnc9KpnV6hNhr+ddxWqh8MT5cnwnYU90KOXBJ4jskn0V6iPg0QFRe3Qih+80o+LlcVAnEAWuxpuWslMceRgY3D0meoiD6IOc5NJyLsEObORisFoMA1/MBXOm59hTIAguM=,iv:pbVlIIzsT9JYxNODmWN9cuvs2YCue6Q2X1sdExICfU0=,tag:xdUBnk673acqE6dDb1WjFg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
