---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./alertmanager-ntfy/ks.yaml
  - ./ntfy/ks.yaml
  - ./snmp-exporter/ks.yaml
  - ./unifi-poller/ks.yaml
  - ./victoria-metrics-k8s-stack/ks.yaml
