apiVersion: v1
kind: Secret
metadata:
  name: ntfy-config
stringData:
  server.yml: ENC[AES256_GCM,data:Gz0zhlm4RJpC4VSxnM3VWqn3Y8IpFN4ADt3ZgQWFnXiia8XiwqzerbwVyNlq9f/f2xYnJpEgKwBDQasb9MM/T9PR1zD1/sPPTHUavVnLpnquBRywb1zgVb/nCdWRDITwMh9wMwP7mj/s+EtseP3UC8iE9lFPCOB9mM2NFL+vnDzeHQLoD/lDsMv0xXd/RwbLTyBbL6Tv0VOLeBK4iOwzoFIlNtXZvH/SFj4m0BaHYKtFH1TpNgkHFQJdfE8jS3C0JRUrA6GF8LPUER0gaGr8l0M0D/bpgFkYNIi3k4bpxq464XIaQqz1/BOSTSzFDeeXZpSJzDVkfgF8+lhyKZLCnJx/UBATL2ah0QNM7OOyHYMFJUyuosneNmWz1qnrMcOYUAcPg+pTK11rai8SXQPMZ5kEYlYlOrYQOkmA8gIwxaQ3EYmAHCXY66MD4sgzhj3sdkwoXzeQNO3cOLL3+4ZMHMHVj+XTpTJjf2cLsrXzXf8bl+Xebe+qbdvR5EII0y7FUqyjg4mU9xEYAvnA3jy8tGCnjm03MrwMkNMVeok6j2zEsWRF38XFID2DsbBYwqyG3vfzLFha6cSFpBDkxadBqc1sPdZNsZF7TG5KtzuVPazHwpx1Tqh2Zv7x9CO0BwGLdVjXCrErUhNWtdBTNCDOEqWgsHtx,iv:OhIQgqRm79jXgwoZzXdLILhQJkGJh3HLSkiuZQEuB/4=,tag:atMn/L5L4rqQgu5YzxkxJg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RjdZdEd0cmp3d24vSEkz
        WlAxbmhzS2lMcW5BTm1hb0JrTmtkczdUMFJ3CkVGTDRHTW9RNTl4cDlLTWxrNHc1
        ek9vSUw1RzFRQVdVa0FxUlh6a3FWa0kKLS0tIGdaZnh5UkplRzNLTHRYVXJkMXlQ
        THdrdENTMGRvSEZtSlBvTU9WcFZvMjAKR26Ymtx9tYa3SSa/L4aJagmiQp6w3hEw
        lgG3NWTu4Lz5IRmbhmvA45YJUltmK/UJkDNlP7/nD/+adWpKW0S8bQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-14T18:51:54Z"
  mac: ENC[AES256_GCM,data:t4T8iUb1vim9S+eRDh6RzPTMP5IFhHCuo/+15ackxef5OzaW5ZPf76tfgaTM96498DL92+loFytFa9lXyeEyeXB96NUqBqpzVH6WNNDCK9Hakx9+J+9lRx7rOX+hHXbJifJGJb8FbdKP7Tfx02CnmtSHeS/54wdtBXpmFrEy6kQ=,iv:SMBhjmVjhjWBVl2WZf3euC1awINpfNcyaW8yFgQmv1I=,tag:RpdhC0UxvLBZt7wF3FQLVg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
