apiVersion: v1
kind: Secret
metadata:
  name: ntfy-config
stringData:
  server.yml: ENC[AES256_GCM,data:MAoVvM/Jc2XtEbhWBF8V9XhufRRfmS8Qz4V/PIJpDsMxL2zrVzDzibTuo16rIHR+ZVhRKLCo6O5xYQOA7BlmiM1f0E/1H+A5ios88H0prTvKx/3ZGk+OwEB4u1wiE0lOm1UBlpImfiAZl00wG4XQflYixeHgtbGScyT9Tg1uAsQ7+6+aWDad/9FHXc13GWosazZ7p+gfKnPBviWxLTMyvfZzWlGVxGwur3PmvRuiTtmu1YD+faepQgg0YL4YgRoWbwZyaKOuViumqhEWeLaEjN31fgN8TOhXWcKNXUXeA9apo06R6W7F5hfIR1rwYW731sB/1Jq2/4whlA7lf/k/n4CdrbJ9mlS9K4wnCdm6VUQOMl9DDq3Vli6LeSqEMk0Fj5ldPgAw3H0fPapmgA0EWqpxk0EwQXDLHeA7h3zNg7JRb3hXgzidQ09wKnTPHCI2AznxWHreWdZfaaS6SMGaTc1ikXvuhFQVIfd4PR2B3lARFV1vowEQBSXrJg/q7fjkE+bVY9Mq5GVh/MOlPsHiEB5BNdK7E2j49WKpfo58t8n5GJFJND0Xx8/jf0TnJyT2oO6LShdi91LhYsIgLrZ7BQQ6smOw8dXF7AAIrPdGmvFhNIQ7Q0F1656osjcXIpxNfEufbvtjhhaCjfWCJRzDeDBz4RELn4sRMLLRq7A6aoVU6R0MQGVYS2ncWDHlje3gpbnwJvhpJMSH/g==,iv:cTBCSIRqIqRjyf64L6rfmmqxbum7r6dm+G0cdsfMxTU=,tag:z9plXB0OsZitnXwEFl0qkQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbXdLV1ozUFhCSHdCdnlN
        RllCVzNjc2YxcUJVcGkzZWVJdFF0WEI3UGtnCldJQnRSZytabSs1YkJUdDAyRXJo
        QlR6dzhxNy8wTzhVdjVKQjFQNjZhUzQKLS0tIEpxZUtCWkpMVEhaWjVFZmxBVURT
        TEFQL2ljVlo3TnloNUsxZXdYQmg0R0UKrituKWaPU0LJw+Bw8ooig3ZloGpkz1Cg
        Ey8UmSihsW41UEVBCvf3EVQQC+PE+K7YgDBj9zfuMywDWBVML7RmUg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-14T19:11:38Z"
  mac: ENC[AES256_GCM,data:fQlOIWf2tiQdKf65k19/f+0wN4TunpisORISy6LgoerJB2VZMa7nDBcyY5NO1vEB1Y+0Evdge+QM3DhBjsgXfVLdWWKpCM+LKA9Y9buEHlR9QhPmGKnyMJwipTCR9ATeUuyg2tCpu3+hwn/hJ9um6F3KjR0j1QmZoBpH9poIfOg=,iv:XBlPvDfKyynpjHMU3dfHO9i9sgNBL5oKvWswPJf9VLs=,tag:m8XqdWVkjfU/Ekt81WTSIA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
