apiVersion: v1
kind: Secret
metadata:
  name: unifi-poller-secret
stringData:
  username: ENC[AES256_GCM,data:hlGGZutuZgw=,iv:RpR3zmixi/GkclWhwYj5E1KH/XI/MXUZ9Lkzoy2YTbw=,tag:TgsB7pjNbTkheuW8Aqz0tA==,type:str]
  password: ENC[AES256_GCM,data:VIUhK6ePo83i2CTOJovhbgesfQ8=,iv:8w6JpYR7G/0ekRzGHK1e6S+eGDTtViOAWvEOHnJzxH8=,tag:bV9qEfxa9K0IRD2KjvQRRw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbGREeGRmZTFXT28xSjI2
        VVdHalQ2eFdlenBCSGlsYzRySm41ci9GSmprClpaME9qUEtPUGd5ZTZialRKWndJ
        OEZCZFIrN3RKYkZ1aDVpR3Vqb3R6NXMKLS0tIGYyRDFIb1dqeDBDK2FmNlZsTFpF
        eTc5L2ZUeTJUaVMvb0xqeDBkYkFDbFEKNElg2FhSxhsm/SddD/1XmHpPXIahJeSB
        epDjG5OGagOY0FgemweNzCiHEO8mFPXkrD5/9HbjxRP6aAMxzBp1vw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-15T11:58:39Z"
  mac: ENC[AES256_GCM,data:mBWYP1TdS8xrkUiu9H0mTfFdVOlx+LJDibPK+LWUusQBa+jfp9RFRA3vLjEzQP0UvciaW4TDUwFHZsbBv8e4QTVC5RLpw6WWJRfq8IYN1SSMdvFkSPKbP2rJ4j0EkYYLx0gVVdu+FdrMvW0oQ8YGsVgxALYrKB1HPIRfYcRGxC8=,iv:NrO8qalDFF/yiiWJT//wgS4q2J4QzyCBii3HYGK3C4s=,tag:EsMKRxSHzWAaNWi1hQeh9w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
