apiVersion: v1
kind: Secret
metadata:
  name: unifi-poller-secret
stringData:
  username: ENC[AES256_GCM,data:a7IAT2OtFs7BOuzW,iv:5z6gbRK4gL/sjJ5gb7CENV9PYTPx24cIY0K4cjbastI=,tag:BSltDWAAg8GnlSqPTs7Sfg==,type:str]
  password: ENC[AES256_GCM,data:wviV3uMmG8B23bzRsR6f+9qHEMo=,iv:nxM/A9DlNTlmsIQ/fU7y0cg+oLKFADg6MsyDSMKuAwA=,tag:5fs3qLBIwgWyLJgmqIVDiA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbGREeGRmZTFXT28xSjI2
        VVdHalQ2eFdlenBCSGlsYzRySm41ci9GSmprClpaME9qUEtPUGd5ZTZialRKWndJ
        OEZCZFIrN3RKYkZ1aDVpR3Vqb3R6NXMKLS0tIGYyRDFIb1dqeDBDK2FmNlZsTFpF
        eTc5L2ZUeTJUaVMvb0xqeDBkYkFDbFEKNElg2FhSxhsm/SddD/1XmHpPXIahJeSB
        epDjG5OGagOY0FgemweNzCiHEO8mFPXkrD5/9HbjxRP6aAMxzBp1vw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-16T21:42:00Z"
  mac: ENC[AES256_GCM,data:ZB9jDquz26W+VSXougbFqF7mwvrFa/WC0BybYZB1Rma6zoN8j9J6m0PYbYSkyDicyfrMtMJamP6v2DgiF6rdD9BqpnAwI2v46J6MwyaOwSqEtpdJbxa+wNNiRL54+P5XFR+quLNbJvaEc0oY0U7FvPK+74ZMyQukdMvP0h4kIos=,iv:wUnQ3SJmS2RIX1ZyYOUqARGCAhdjzbAhTu6VsQ3VHNY=,tag:zuCNFWifXNjsJsqSb9/6Fg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
