apiVersion: v1
kind: Secret
metadata:
  name: mariadb-app-credentials
stringData:
  username: ENC[AES256_GCM,data:L3xsKzv1FnqN4jCOlg==,iv:vP2wI0P5UTCdUWmxUKmC9niw3FDZlcu7lgrsxk/anxc=,tag:D0Yno/Od4Gl/Hg9OBI8Eiw==,type:str]
  password: ENC[AES256_GCM,data:QI6RqhjVVV3cXBLhi8SO/XV0S177gCJf0wGIJ8oX0Q0yqN6qdnYyyVMC/RXW4Xh0,iv:tjxQag539b88eOSkSHBJcHXTSbFUAdgWX9TZ/jMgpTA=,tag:y9JiMUGnkDXOBYvjrDBdjg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcDNxeUlXazF0ckQ4R29L
        bk9NcnB3TWFoLzBXNWl3dStDNThNOTdNaFFrCngxTmxXQnJSMmJtZU9STmJVa1hi
        OGhTRm1UR0xkaGc2S0pXcTlwa2Z1SUUKLS0tIFJnSm5tQnYweWtQLzUvdnBkbWZK
        Z1cwbjBQbnlxK1k0Y1U0aEdZZVI0U1EKjFfySiIAm8nw6Mb6pQJcKzYVvvFo/ucI
        739h5JjWeCGw5xySy+sD1gMyBy4T4+8MlEVeScdI0p0aDXTgybin6w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-16T07:30:15Z"
  mac: ENC[AES256_GCM,data:r+FIp/a58qN1Eladtp4txHZ217J8hYIP4jn0n2NXLR/MO18h1Vql6PNuH2XJEo4Ry/fEDhytiibFV5MZLxL6WeEHBwzXxaAGLSht9SzdKIM0V4ncZkL+to/r/TVgEn8+Sjh5mKSZUKUovBcd9JhFwyDmlvy6v0hnzYkCCnnELMo=,iv:NkBTgos0eWdABOizu+xTagQZQs1c2IvS7pWHdJiHFms=,tag:YrWaopKCPiGwsSbFfxikhA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
