apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
stringData:
  password: ENC[AES256_GCM,data:hAaT4yS1WWR0EEX1njaHRwJZGoLFAjwlE97RYvbZSc4=,iv:cXTtlylvrcQxeznA18DIf1fYcYtBlqqSPR81BZThF5o=,tag:iJVVOW5c575uep0ATpFpQQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVjhyYXJCRWFaOUhlWXl0
        bU1YL0k1dDVzTXZkM05TQmExckh3N2VJeGh3CkZUdjVzbHZ6NWJIUHFkNXJLRnBS
        REdneWJicFpUUldlSEgrczNSN2k0TkUKLS0tIFlycW83cktreGpZRXp3M1RyVUlR
        Qzd6WDd5WjBzbGZJdlN0dkpaWXZjUHMKAmv/iPB9hmkv+IRB6I3bZ+5emYBjUwZ9
        +7l5C9QKFH4g8Zq+YWZUp11ttPP7vBZR1AbBza+KBJzhkmXIqnKJdQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-15T19:26:02Z"
  mac: ENC[AES256_GCM,data:yIcVTxb9+zHitbsRRomsjgA3d+gEzhQyaS5PEebd93znM9kmjgVHUTGIeO5U4yObDaHsuUj9mN0V8Y3U7e/zAyQam5n3rwdRYQ3VfunKbZoP588LCRgU90oOIACr4VYdV82chwjpA1BQv9L/bIGkkbQPdGC/uqZbSFvoVdSrDA0=,iv:CM/ntl5gdigLVcFsnYZRjMkzAsqpBI3kqfVbL59935o=,tag:G6xGXr+aEu7FTWLSPqRJug==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
