apiVersion: v1
kind: Secret
metadata:
  name: mqtt-exporter-zigbee-secret
stringData:
  MQTT2PROM_MQTT_USER: ENC[AES256_GCM,data:jqHQw5JRvLCv24bLBg==,iv:02hDivRrCbNef+U619gQQLaYo3l5dnlIHImedwO4t+M=,tag:QTxiRmEjrrRdls2a3gPRYA==,type:str]
  MQTT2PROM_MQTT_PASSWORD: ENC[AES256_GCM,data:5NGA+htI7mRWj8ruHyVcTdC4dJrHQR0x,iv:eWJ4uZ9hpTRHXThUb7PX4d3viJyAWm7fodiv0vBzVFg=,tag:joLtG+IjZLPzfgDWWUY6HQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMEEvUlRIZXNiRUxhQWhu
        YndMSHJZOGhDNDBzZzJJckR3QXlZRlVDd0VnCkFTQjZKMm9yV2U3bjNlekI1dXM4
        WkZJSmtpUkUrQnVBRkpMZ3JaSFYzSEkKLS0tIGpQRytVaGY3THVGN090STJQTTNN
        QmZZdk9na2lFd0FkY2U1TUVrTjNZU3cKji2x2VuVXHl/77HxVdXXg7kfnTmsdsMi
        Y1HQXV3hEMXm7VKZoAxP0lz33JiHDkhT+2guQd8jcoAsS7udzJgoTA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-18T22:48:07Z"
  mac: ENC[AES256_GCM,data:+32QHhZ6g1kAoEU5VD9fLdJfC7ERu7PnfEpf8gROUfYe7xiFaRTvXRC+HQGjGoRZe5wj2tlHrKkocLpRjCFO6UUFrKq6kNmoGBXSMHTpvqGT1pWyKAJ6mouXC68rUu4AzEe2Pnd9UuJJvTOi0yfvsHZkTsjtDnlbsTPSabogGkM=,iv:lEQBBdC8wwY8SeqOZY5UZ6trilTc0paSYVOa8l5bmV8=,tag:Eg7F/wxnMPly5PeEu3lIsQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
