apiVersion: v1
kind: Secret
metadata:
  name: homepage-secret
stringData:
  UNIFI_USERNAME: ENC[AES256_GCM,data:W8uEabDxa949QxAf,iv:xIQjz6/5fc2GOGekQqjduj/I+DJgIdIEIX/0yOZYDnE=,tag:RRfZvcO7RylXMhU2g3t1Vw==,type:str]
  UNIFI_PASSWORD: ENC[AES256_GCM,data:2ygYPzb07aFOPYePv2yzLm24kiY=,iv:t2/ofXRFRWWRqvZ92mlYVg9G/mh+ORPwANxXQCjMD38=,tag:idIrjv79EESLz9rEp5I8RQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRlNHS0pFMnlOQTczRTNF
        Z3RVajA4Mng5UFRqODJMaDB0RldTTGNsVDFFCk9HdFIvUzhvZ3VYVE5BVHdSQ0k2
        MURTSVhmeG4vMUo3VHJGd3hTcFpHMTQKLS0tIDVHaEgzcElvREQ1NU9UVXplemZM
        YWZOVktWM0RsU2NQeEtUUG5ZUkZlY1kKkeU3NsAQWrqOgK2IbWVtAuY9H1kyok9i
        winR1litM3ZU08KQdtgdQvb2gwZsUUh7gQg1Hn7voA8YbLitqD8Rrg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-17T13:29:52Z"
  mac: ENC[AES256_GCM,data:lDaBDTMENYcFAxur9s3C32Cjdk+3Lpu62HQvZHDBmupD2ia8dO+fWyv24bOm3CHyprkv1WQ6p7sVPEoq0g9ulBrGWUYN6xUBOHf+YCseZi4+zo5spBhQ/NE5Z9ZPy2Pa1RU8xmhXzaPSkFJg0/+rOL5AzwgvpB4GtNjkX7zFWqM=,iv:E0BgB9P1+7v3xnuDm1y6ESDhhoNIUmgYCcW2lzhWi+w=,tag:/Mdj0CWATdzJPeT4LZkJ4Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
