apiVersion: v1
kind: Secret
metadata:
  name: frigate-mqtt
stringData:
  password: ENC[AES256_GCM,data:EUVwX0r3Yn5CC9aU5/ABA3jAgzibBrz/,iv:eWOjp6SzKv2/aLdV5UxXrfhM4v6rVXFwHPxWIjhMiqA=,tag:2zUahrD7sNV6BW71q/xtMQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2eFU3a0hXbFdpTm5IYTE5
        SXAxV3lVWEdxVFd4Vzg3eTc1aWpBU0RDZkYwCk1PdHRueU01aHNSM2dUZ3M1Nnhq
        Z250MUNSeVJ0dnNQZFdtNHdBWHFMSEEKLS0tIHZ3ckMrQnR5NG9mSGZFamp1UHBK
        UVJaRGxtOTBOZCtKQVE0TXoyUGdMbjgK+enTB0zmP5pFXhJYgxK5RFQQ20dfpCzH
        mdKc5REEhCuyNaye+AYp47DKU/ObRbAIVm//5QzU/AyCVYsSHIGoMQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-11T21:36:35Z"
  mac: ENC[AES256_GCM,data:xgBImzPZEmFyKgDAyvrvb6kmdbvbCnMRHD7oqbMp0gh3t98i3I9xQFDYaPPrqG2xOgFB0MiwxDaMSblbKNtP9JUMPiDue1w4DzbgJHwvEVH1IwiS2ss7Y1/5BmwmD0zLHvZyfH3odsMcv1wA+MK184tHlXzi21xv7BbPOegOrys=,iv:cum7uy9/xTkG00X6LGejrZTvwtfRPAyBUaJP8zgNMOU=,tag:r8gTtvk6wd9yTJ4SLP56+Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
