apiVersion: v1
kind: Secret
metadata:
  name: frigate-secrets
stringData:
  mqtt-password: ENC[AES256_GCM,data:uZk42rAC7yqFrAICmb1FqmeBJIqjyb0SU2xnFHQ3,iv:45J+KShlin8sZHazW+bberzaJHvEG9+u1yz/IYroYMI=,tag:VtJBwPslUtbJ+0OrvpwuIg==,type:str]
  washroom-camera-password: ENC[AES256_GCM,data:SCHrwwg4X0A=,iv:PDPyGkUj74ecKxy8nkMTcEaxkAANANPcnhDZe+JXYvU=,tag:t3euEpXXIPmJ02v7nsELWA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSVR0TDhOaEFndFZlTFR0
        NG82MnkwOTRBRzVndHNqNmhrUUFYaHVOUVJnCloyVmJVVS9xTFlwV1I4SGVmZTlS
        ZW9GLzYvSnBJZmVvUm5qTnBVZ3dtOGsKLS0tIElGZEdCTTNJb1BDZlorWWFVZm5P
        Nzk3dzhyRFdJdnRWUXRCZmJUSnhYUFkKoIG/vVjz0x6dkak/uB1095UC4IoYTp/o
        I5eFWmXrlUXXUJ4Nz2zBeDEZLl6GrpcHYC5b66OAGe0s0W/gZZG3dw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-23T21:44:21Z"
  mac: ENC[AES256_GCM,data:YKbBu4tq49RbIoAUBnEmtGPjLg2ChRRzwDAnGZ6TeG9gnHgwLFjK6Xu7gQOZMn2NOPy/ePC4Pf21MHwji0nwhRVq64D9aZvXogR7VYABv53YuhCu3FzqejoDHET6QIwYj4uO3tOzu9FS70F0rJUv+/ve6Gvp0A/7wRPxf3UXlk0=,iv:aDl0n2AKmtRz+o2NUCxNBbzSLNhHIM5E+n6GIbmtVns=,tag:QGyPEfdyioyBG1RqZCG6cQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
