apiVersion: v1
kind: Secret
metadata:
  name: frigate-secrets
stringData:
  mqtt-password: ENC[AES256_GCM,data:jVFet4RIsWh9oRgXHjmTv9YoJvem8l5z,iv:ASZXdbl6jrRc3YEAEPdvBbrD5+tf97cjV6DvOVin01Y=,tag:yQOz+jo632AJn+d5Sp3ovw==,type:str]
  washroom-camera-password: ENC[AES256_GCM,data:SCHrwwg4X0A=,iv:PDPyGkUj74ecKxy8nkMTcEaxkAANANPcnhDZe+JXYvU=,tag:t3euEpXXIPmJ02v7nsELWA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSVR0TDhOaEFndFZlTFR0
        NG82MnkwOTRBRzVndHNqNmhrUUFYaHVOUVJnCloyVmJVVS9xTFlwV1I4SGVmZTlS
        ZW9GLzYvSnBJZmVvUm5qTnBVZ3dtOGsKLS0tIElGZEdCTTNJb1BDZlorWWFVZm5P
        Nzk3dzhyRFdJdnRWUXRCZmJUSnhYUFkKoIG/vVjz0x6dkak/uB1095UC4IoYTp/o
        I5eFWmXrlUXXUJ4Nz2zBeDEZLl6GrpcHYC5b66OAGe0s0W/gZZG3dw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-12T07:12:35Z"
  mac: ENC[AES256_GCM,data:ZOVCb9fSIJ6P89CzEslk9HVUSBV+DligsCImm3U4YkBfcaU6Rsvots405o2oPiTzF5p3uQoXRShZ3mj4LHRXfT/ceKACz8wLS+9Yflr7Ty+vpytJpmxPgC8E5SV+80JuXRBW5cZ5PoEa3z5ZRv0RR34y2T4SfaZzZcdyn/sq9TE=,iv:ib+VXXVqaDSzcUbpTFOusC+ODi0VcofuNWyunY6edCI=,tag:u4IMHq6A78XQhBNofQl4ow==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
