apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-github
stringData:
  username: ENC[AES256_GCM,data:WYBTWlIw56w=,iv:XL7DlMPSNS39sq3d+htQ+5U7N+pAySIdydR9uAtI5rQ=,tag:7uaBNO4+ZJRKXhH6jJRFCA==,type:str]
  token: ENC[AES256_GCM,data:XaXj9Ms8BVWGozzxBTKUvMm3MYQ6/0Ea0vY1zlAxkAPqfk8K3+56yD1s9KbKBOInJiOoo4ou7isx9+FpWYFzCTgfLA0LsKawErFi9BkMpHWdhZuAGfn8WghyzQUw,iv:dot/m6yOJ0oFpJYmOq/kV1EJeBcuoPeCqpCVpl/bEOE=,tag:jOb4lBvOeVcSzt6v4/6MNQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVazluZ01pVHByMjhaMGg0
        Sy9maTBsVW5ZSlBsNVVFT0dBNGJETkZFVFZ3Ckl2YlhBR3l4a2YzVWhhOWpuQ3Y2
        d25hME9hV0hucXo0YVEwYW5nRTVVRWMKLS0tIDVMdldtRkEvYlVobU44aVg1OXR2
        M1NTVGpOaG9saVVHcWVJSi9VMWFyeXcK1wIn2PMfLXTKh2ftD0fXKyfaIEXithSh
        ZW820+z7lRoO+GrWJdBof5zqCq0zYkQ+goPn8d3Bf4+zEoYKTqJ/VQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-16T17:06:25Z"
  mac: ENC[AES256_GCM,data:nIHA5PPwZl3QV8fi9TlE/KX9mpOXs2wWVQSbgTytQV4lOKYXdMut+nPCaOahxkbWzrBbUC5OG7P8XZBfjbCsfYZr2NQQVDDElHMiRyFWkGfm20q6WKK6TKRHmmJp4wHo+eOQILIjn1Jid72GYjVZXznYE2Q7Rrl407fz/qwP6qI=,iv:iuSPYEoTehPx3EfJsp849MJmtfXq4Um+miPdjtUCDNw=,tag:VZSpw0zddeC2eBuRvISpFA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
