apiVersion: v1
kind: Secret
metadata:
  name: ha-code-password
stringData:
  password: ENC[AES256_GCM,data:7OjOzfkzYhdML4t9yiMDmntWvRc/PTfF,iv:hbn6G/JH5w6aOL1rJv7T2//3bEfpO64c2fL/dvv6J1Q=,tag:jIXt0Xlw2qCVodnUXBgRMQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZk5iemNJbFp6MU5XUjRJ
        Q0pML2YzSnRJK3o5bU5LYjNuakczWjJ0NkQ4CnQ5bEo3OTRMdHNTbXpRNm9ZU1Fz
        U0s3aWpSaFVucG55MlR1eHNNcHBGdUkKLS0tIDE4U29VTVlxQkkzUllwYndDMDZp
        NGh5YVcvSUZINmFHL1VCUFNPZ2w0RzgKbHnCxaNXlEnnMf3gffVAzwY4lSbYK9/7
        vT7tGZJzs3wBAtvgDqLz/GmdyLMY0qN7xv+jyGdF8B2hy8aGpqclag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pap96q8ferlm2cu3xuwvc7rxaex0dfxuh7jxccmrncz7lfs3qydq28zrpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-16T07:38:07Z"
  mac: ENC[AES256_GCM,data:fuZw/lGl7mi5TT/SB1OLP6WcNQnb7Euw+8CXJdUv60LR3V0XWn7VyGtBLRcpALhI5GEXYqq1ITyxJQ5+GqkckeUeLDfSZLsScYB/DDqj076n52UT7Kz85bp9qqvtmzBfc3FrDMAsAJ87/s1xypX+YbS6nBcimTGI2q/rqrvXXYA=,iv:uqK4TiYn3ovsOKYanAP17Y0pdCsRdeBbdseMTWjAzhc=,tag:8S3qbB+afVuN0TglotvG4w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
